ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: whoami.conxtor.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - whoami.conxtor.com
      secretName: whoami-tls
